### ISSUE TITLE
cas登出问题

### ISSUE THREAD

**Issue by wanglongsxr** [zhangjunabc/nginx-auth-cas-lua#2]
按照你的配置，我访问http://ip/cas-logout时，出现了以下问题：
`2021/09/25 09:52:55 [error] 8#8: *25 lua entry thread aborted: runtime error: /etc/nginx/lua/cas.lua:146: attempt to concatenate local 'local_logout' (a nil value)`
然后我在你的代码里修改为
```lua
local function logout(local_logout)
   store:delete(_get_sessionId())
   _set_our_cookie("deleted; Max-Age=0")

   if not local_logout then
      -- redirect to cas logout
      ngx.redirect(cas_uri .. "/logout")
   end
end
```
然后就好使了，这是什么鬼？？

**Comment by ezhangjun** [comment]
调用登出方法时，logout方法要传一个参数，已更新到文档中
location /cas-logout {
    access_by_lua_block { require('cas').logout("**http://your-sso-server-domain.com/login?service=http://your-website-domain.com/**") }
    root   html;
    index  index.html index.htm;
}
